### ISSUE TITLE
building aur fail which is caused by file extension name

### ISSUE THREAD

**Issue by jackyzy823** [maximbaz/docker-arch-build-aur#7]
Running
```
/bin/bash -c '/build-aur standardnotes-desktop'
```

result:
```
mv: cannot stat '*.pkg.tar.xz': No such file or directory
```

After digging into container, i found that the built package ends with "pkg.tar.zst" not ".tar.xz"

Reference: https://www.archlinux.org/news/now-using-zstandard-instead-of-xz-for-package-compression/

**Comment by max-baz** [comment]
Good catch, thanks!

**Comment by max-baz** [comment]
I went for a hopefully future-proof approach, let me know if you still experience any issues!

**Comment by jannikw** [comment]
The `.` after `tar` prevents using no compression at all.
https://github.com/maximbaz/docker-arch-build-aur/blob/5671cb477431ad534511624fbf16239a66921d86/build-pkgbuild#L16
So when specifying `PKGEXT=.pkg.tar` moving the package fails again.

I also noticed a related problem that is caused by the asterisks for moving the package. For example the AUR package [zoom](https://aur.archlinux.org/packages/zoom/) downloads an archive and calls it `"${pkgname}-${pkgver}_orig_x86_64.pkg.tar.xz"`. After building the package (which basically repackages the archive) one is left with two archives called `zoom-5.2.458699.0906-1-x86_64.pkg.tar.xz` and `zoom-5.2.458699.0906_orig_x86_64.pkg.tar.xz`. Since both match the pattern, they will both be moved to the target directory. This isn't too bad, but not perfect either.

A possible solution I can think of is using `PKGDEST` from [makepkg.conf](https://www.archlinux.org/pacman/makepkg.8.html). Since the makepkg user will probably have no write access to the `/pkg` directory, the directory cannot be specified directly using the variable. But one could specify a temporary empty directory. After building the packages that directory should only contain the package file, which means all files in that directory can be moved to `/pkg`, simplifying the glob pattern for moving the package further and avoiding problems with the file extension.

**Comment by max-baz** [comment]
Sounds good, would you be able to submit a PR? I don't want to over-complicate the scripts but your proposal sounds like it could be just one or two extra lines, so why not 😉

**Comment by jannikw** [comment]
Sure, i will give it a shot.
